### ISSUE TITLE
Unknown fps unlock

### ISSUE THREAD

**Issue by Slayerrobby** [LaszloR1/RPCS3-GTAO-Tutorial#4]
Hey, I was just wondering if theres a small tutorial of how to setup 60fps for the emulation? I've tried to look up patches but they are for later versions of the game.

**Comment by LaszloR1** [comment]
This one was made by @zonedkitty, but I personally never tested it. Give it a go.

```
PPU-4480a60933317c18131e6c1ffa0c798e1f484404:
  "60 FPS":
    Games:
      "Grand Theft Auto V (Grand Theft Auto 5)":
        BLUS31156: [ 01.06 ]
        NPUB31154: [ 01.06 ]
    Author: "DakrFH"
    Notes: "set vblank to 120hz"
    Patch Version: 1.0
    Patch:
      - [ be16, 0x0045fb5c, 0x4800 ]
```
